import { CardId, DeckConfig } from '../types';

export const DEFAULT_DECK_CONFIG: DeckConfig = {
    4: {
        [CardId.DEATH_NOTE]: 1,
        [CardId.ARREST]: 1,
        [CardId.GUN]: 1,
        [CardId.FAKE_NAME]: 1,
        [CardId.ALIBI]: 1,
        [CardId.WITNESS]: 0,
        [CardId.SURVEILLANCE]: 1,
        [CardId.VOTE]: 2,
        [CardId.EXCHANGE]: 4,
        [CardId.INTERROGATION]: 4,
        [CardId.SHINIGAMI]: 0,
    },
    5: {
        [CardId.DEATH_NOTE]: 1,
        [CardId.ARREST]: 2,
        [CardId.GUN]: 1,
        [CardId.FAKE_NAME]: 1,
        [CardId.ALIBI]: 1,
        [CardId.WITNESS]: 0,
        [CardId.SURVEILLANCE]: 2,
        [CardId.VOTE]: 3,
        [CardId.EXCHANGE]: 4,
        [CardId.INTERROGATION]: 5,
        [CardId.SHINIGAMI]: 0,
    },
    6: {
        [CardId.DEATH_NOTE]: 1,
        [CardId.ARREST]: 2,
        [CardId.GUN]: 1,
        [CardId.FAKE_NAME]: 1,
        [CardId.ALIBI]: 1,
        [CardId.WITNESS]: 1,
        [CardId.SURVEILLANCE]: 2,
        [CardId.VOTE]: 3,
        [CardId.EXCHANGE]: 5,
        [CardId.INTERROGATION]: 6,
        [CardId.SHINIGAMI]: 1,
    },
    7: {
        [CardId.DEATH_NOTE]: 1,
        [CardId.ARREST]: 2,
        [CardId.GUN]: 2,
        [CardId.FAKE_NAME]: 2,
        [CardId.ALIBI]: 1,
        [CardId.WITNESS]: 1,
        [CardId.SURVEILLANCE]: 2,
        [CardId.VOTE]: 4,
        [CardId.EXCHANGE]: 5,
        [CardId.INTERROGATION]: 7,
        [CardId.SHINIGAMI]: 1,
    },
    8: {
        [CardId.DEATH_NOTE]: 1,
        [CardId.ARREST]: 2,
        [CardId.GUN]: 3,
        [CardId.FAKE_NAME]: 2,
        [CardId.ALIBI]: 1,
        [CardId.WITNESS]: 1,
        [CardId.SURVEILLANCE]: 2,
        [CardId.VOTE]: 5,
        [CardId.EXCHANGE]: 6,
        [CardId.INTERROGATION]: 8,
        [CardId.SHINIGAMI]: 1,
    },
};
